name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pass: ${{ secrets.PASS }}
        WITH_V: true
    
    - name: print secrets
      run: |
        echo $DEV_ENV_FILE &gt;&gt; src/.env
        cat src/.env
      shell: bash  
      env:
        DEV_ENV_FILE : ${{secrets.PASS}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DEV_ENV_FILE
        path: src/.env 

    #- uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: pytest 
